[package]
name = "gmsh"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
libc = {workspace = true}
thiserror = {workspace = true}

[build-dependencies]
bindgen = "0.71.1"